name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort mypy
    
    - name: Run ruff
      run: |
        ruff check .
      continue-on-error: true
      if: hashFiles('src/**/*.py') != '' || hashFiles('polarctic/**/*.py') != ''
    
    - name: Run black
      run: |
        black --check .
      continue-on-error: true
      if: hashFiles('src/**/*.py') != '' || hashFiles('polarctic/**/*.py') != ''
    
    - name: Run isort
      run: |
        isort --check-only .
      continue-on-error: true
      if: hashFiles('src/**/*.py') != '' || hashFiles('polarctic/**/*.py') != ''
    
    - name: Run mypy
      run: |
        mypy .
      continue-on-error: true
      if: hashFiles('src/**/*.py') != '' || hashFiles('polarctic/**/*.py') != ''
